baseURL = 'https://micahel-harmon.com/'
languageCode = 'en-us'
title = 'Mike Harmon'
theme = 'hugo-coder'


[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


[params]
author = "Mike Harmon"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Mike Harmon's personal website"
keywords = "blog,data,ai"
info = ["AI/ML Engineer & Data Scientist", "PhD in Computational Applied Math"]
# avatarURL = "images/me.jpg"
#gravatar = "mdh266@gmail.com"
dateFormat = "January 2, 2006"
since = 2016

# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/mdh266/newsite/tree/"

# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 10
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = ["scss/coder.scss","scss/coder-dark.scss"]

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/mdh266/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/michaeldavidharmon/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@mdh266"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
